name: tests

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.4'
    
    - name: Run tests
      run: CGO_ENABLED=1 go test -p 1 -tags netgo -timeout 20m --count 1 -race .
